version: '3.8'

services:

  shaun-app:
    container_name: shaun-app
    hostname: shaun-app
    image: node:l
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        LOGIN: ${U_LOG}
        PASS_WD: ${U_PWD}
    networks: 
      - shaun-net
    volumes:
      - shaun-data:/data
      - /home/shaun/Program/dockerfiles/dIDE/volume:/home/shaun/volume
      - /run/snapd.socket:/run/snapd.socket
      - /var/lib/snapd/snap/bin/solc:/var/lib/snapd/snap/bin/solc
    privileged: true
    shm_size: 2gb
    env_file: 
      - .env

networks:
  shaun-net:
    external: true
    name: shaun-net

volumes:
  shaun-data:
    external: true
    name: shaun-data
